services:
  db:
    container_name: eventdapp_db
    image: "bitnami/postgresql"
    environment:
      - PSQL_USER=postgres
      - PSQL_PASSWORD=postgres
      - POSTGRES_PASSWORD=postgres
    tty: true
  server:
    depends_on:
      - db
    image: eventdapp/server
    environment:
      - DB_HOST_NAME=eventdapp_db
      - DATABASE_URL=postgresql://postgres:postgres@eventdapp_db:5432/postgres
      - COOKIE_SECRET="b6fe3b29-afb9-46c2-9983-385786e064b6"
      - PORT="5000"
    ports:
      - 5000:5000
    build:
      dockerfile: ./server.Dockerfile
