# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and do a deploy run
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]        
    steps:        
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Try Deploy
      run: docker compose -f docker-compose.yml up -d
